### PR TITLE
Convert values into the inner values

### LINKED ISSUE #3: Convert into the inner value
What do you think about providing accessors for converting into the inner value? Like so:

```rust
pub fn into_variant(self) -> Result<VariantType, Self> {
  match self {
    Self::Variant(x) => Ok(x),
    _ => Err(self),
  }
}
```

### PR DESCRIPTION
**Pull request by NeoLegends**
Fixes #3. I also ran rustfmt over the codebase (hope this is okay). :)

### CODE REVIEW

**Comment by NeoLegends** [comment]
Ah gosh my fork is too old. Have to fix some errors regarding syn. Just squash the commits when you merge eventually.

**Comment by NeoLegends** [comment]
Wait no, master is broken as well. @bluejekyll Care to fix that yourself?

**Comment by NeoLegends** [comment]
Okay, this now has all the changes required for syn 1.0 and proc-macro2 1.0. *Tests pass*

**Comment by bluejekyll** [comment]
Sorry for the delayed response on this. It looks good. Thanks for the PR. Once tests pass I'll merge, then I'm planning a new release.

**Pull request merged**
